apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
  annotations:


spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system

  source:
    repoURL: https://github.com/nagarajurahul/helm-charts
    targetRevision: main
    path: gatekeeper

    helm:
      valueFiles:
      - values.yaml

  # ---------------------------------------------------------------------------
  # VERY IMPORTANT: Ignore CRD diffs
  # Helm manages Gatekeeper CRDs; ArgoCD must not fight it.
  # ---------------------------------------------------------------------------
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  - group: batch
    kind: Job
    jsonPointers:
    - /spec

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    # REQUIRED for Gatekeeper + CRDs + webhook
